---

- name: Install xmonad and xmonad-contrib
  pacman:
    name:
      - xmonad
      - xmonad-contrib
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  dealy: 2

